#define WATHER_API_SW 13
#define SERVO_MODE_SW 15
#define SPK_STATE_PIN 25
#define LED_R_PIN 17
#define LED_G_PIN 18
#define LED_B_PIN 19
#define TRIG_PIN 26
#define ECHO_PIN 27
#define SERVO_PIN 16
#define SERVO_CONTROL_PIN 34
#define PASSIVE_BUZZER_PIN 2
